version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'vivekm'
      MONGO_INITDB_ROOT_PASSWORD: 'DrzErx7M7QePNjFW'
    volumes:
      - /var/databases/mongodb/codershouse-data:/data/db
  
  backend:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend/
    container_name: backend
    restart: always
    ports:
      - "5500:5500"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env
    volumes:
      - ./deploy/default.conf:/etc/nginx/sites-available/default
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
